server:
  port: 8084

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: employee-service
            uri: lb://employee-service
            predicates:
              - Path=/employees/**
          - id: department-service
            uri: lb://department-service
            predicates:
              - Path=/departments/**
          - id: review-service
            uri: lb://review-service
            predicates:
              - Path=/reviews/**
          - id: eureka-server
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/main
            filters:
              - RewritePath=/eureka/(?<segment>.*), /$\{segment}
          - id: eureka-server-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# enable tracing in the department-service:
management:
  tracing:
    sampling:
      probability: 1.0

# okta configuration for api-gateway
okta:
  oauth2:
    issuer: https://dev-49598244.okta.com/oauth2/default
    audience: api://default
    client-id: 0oahazdi0bawyl63x5d7
    client-secret: nELePEtm1uxIq4RjeTyYIQ2najkThHR36XolBavQnYCcRUJy1VjpHv0fVwTloeJ2
    scopes: openid, profile, email, offline_access